// MeowFolio – Shared Tailwind Configuration
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#e6e2dc",
                "surface-container-high": "#ebe8e2",
                "surface-container": "#f1ede7",
                "surface-container-low": "#f7f3ed",
                "surface-variant": "#e6e2dc",
                "surface-bright": "#fdf9f3",
                "surface-dim": "#dddad4",
                "surface-tint": "#9d4223",
                "surface": "#fdf9f3",
                "background": "#fdf9f3",
                "on-surface": "#1c1c18",
                "on-surface-variant": "#56423c",
                "on-background": "#1c1c18",
                "inverse-surface": "#31302d",
                "inverse-on-surface": "#f4f0ea",
                "inverse-primary": "#ffb59d",
                "primary": "#9d4223",
                "primary-container": "#f4845f",
                "primary-fixed": "#ffdbd0",
                "primary-fixed-dim": "#ffb59d",
                "on-primary": "#ffffff",
                "on-primary-container": "#6c1e02",
                "on-primary-fixed": "#390b00",
                "on-primary-fixed-variant": "#7e2b0d",
                "secondary": "#655781",
                "secondary-container": "#deccfd",
                "secondary-fixed": "#eaddff",
                "secondary-fixed-dim": "#d0bfef",
                "on-secondary": "#ffffff",
                "on-secondary-container": "#62547e",
                "on-secondary-fixed": "#21143a",
                "on-secondary-fixed-variant": "#4d4068",
                "tertiary": "#3d6751",
                "tertiary-container": "#81ad94",
                "tertiary-fixed": "#bfedd1",
                "tertiary-fixed-dim": "#a4d1b6",
                "on-tertiary": "#ffffff",
                "on-tertiary-container": "#17412d",
                "on-tertiary-fixed": "#002113",
                "on-tertiary-fixed-variant": "#254f3a",
                "error": "#ba1a1a",
                "error-container": "#ffdad6",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "outline": "#89726b",
                "outline-variant": "#dcc1b8",
                // PreAuth landing page aliases
                "charcoal": "#2D2D2D",
                "coral": "#F4845F",
                "lavender": "#C9B8E8",
                "mint": "#A8D5BA",
                "cream": "#FDF9F3"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Inter"],
                "label": ["Plus Jakarta Sans"]
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            boxShadow: {
                'tactile': '4px 4px 0px 0px #2D2D2D',
                'tactile-lg': '8px 8px 0px 0px #2D2D2D',
                'tactile-sm': '2px 2px 0px 0px #2D2D2D',
            }
        },
    },
}
